[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trading-sdk"
version = "0.1.10"
authors = [
  {name="Marcel Claramunt", email="marcel@tribulnation.com"}
]
description = "An abstract, fully-typed, async Python SDK for automated crypto trading. By Tribulnation."
dependencies = [
  "lazy-loader",
]
requires-python = ">=3.10"
readme = {file="README.md", content-type="text/markdown"}

[project.urls]
Github = "https://github.com/tribulnation/sdk.git"
